#! /bin/sh
start() {
	origmap=$(xmodmap -pke | grep -E "^keycode[[:blank:]]*?65")
	#newmap=$(echo ${origmap} | perl -pe "s/65[[:blank:]]*?=[[:blank:]]*?space/65  = Control_L/")
	newmap=$(echo ${origmap} | perl -pe "s/ space/ Control_L/g")

	xmodmap -e "$newmap"
	xmodmap -e "keycode 255 = space VoidSymbol VoidSymbol VoidSymbol VoidSymbol"
	nohup s2c >> ~/.Space2Ctrl.log 2>&1 &
	sleep 1 # Don't ask me why but we need to wait more than one second else the ctrl modifier is
		# reinitialized to XK_Control_L XK_Control_R as soon as keycode 65 is pressed!
	`xmodmap -e "add control = Control_L Control_R"`
	exit 0
}

stop() {
	origmap=$(xmodmap -pke | grep -E "^keycode[[:blank:]]*?65")
	newmap=$(echo ${origmap} | perl -pe "s/ Control_L/ space/g")
	xmodmap -e "$newmap"
	xmodmap -e "keycode 255 ="
	xmodmap -e "clear control"
	xmodmap -e "add control = Control_L"
	xmodmap -e "add control = Control_R"
	kill -s TERM `pgrep s2c` 2>&1
}

case $1 in
	start)
		echo "Starting Space2Ctrl"
		start;;
	stop)
		echo "Stoping Space2Ctrl"
		stop;;
	*)
		echo "Please pass start or stop";;
esac
